name: CI

on:
  push:
    branches: [main, master, develop, docs/**]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    name: 测试和代码覆盖率
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 安装依赖
        run: npm ci

      - name: 运行代码检查（如果配置了 lint）
        run: npm run lint --if-present

      - name: 运行测试并生成覆盖率报告
        run: npm run test:coverage

      - name: 上传覆盖率报告到 Codecov
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '20.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
